site_name: Example Documentation
site_description: "Automatic documentation from sources, for MkDocs."
# edit_uri: "blob/master/docs/"
site_dir: "site"
watch: [mkdocs.yml, README.md, example/functions]
copyright: Copyright &copy; 2023 Oscar Dyremyhr

nav:
  - Home: index.md
  # defer to gen-files + literate-nav
  - Code Reference: reference/


theme:
  name: material
  logo: logo.svg
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference

extra_css:
- css/style.css
- css/material.css
- css/mkdocstrings.css



plugins:
  - search
  - markdown-exec
  - gen-files:
      scripts:
        - scripts/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.txt
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [example]
          import:
          - https://docs.python.org/3/objects.inv
          - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
          - https://mkdocstrings.github.io/autorefs/objects.inv
          options:
            separate_signature: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
  - minify:
      minify_html: true

markdown_extensions:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.details
    - pymdownx.magiclink
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
        slugify: !!python/object/apply:pymdownx.slugs.slugify
          kwds:
            case: lower
    - pymdownx.tasklist:
        custom_checkbox: true
    - toc:
        permalink: "¤"