[tool.poetry]
name = "MKDOCS"
version = "0.10.0"
description = "An example of MKDocs"
authors = ["ossinova <oscar.dyremyhr@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/ossinova/mkdocs/"

[tool.poetry.dependencies]
python = ">=3.7,<4.0"